---
# file: upgrade-debian-like.yml
- name: Upgrade Debian/Ubuntu hosts to latest packages
  hosts: all
  become: true
  gather_facts: false
  ignore_unreachable: true

  vars:
    # Upgrade strategy: "safe" (like apt-get upgrade) or "dist" (aka full/ dist-upgrade)
    upgrade_type: "dist"
    # Only refresh apt cache if it's older than this (seconds)
    cache_valid_time: 3600
    # Reboot if /var/run/reboot-required exists
    reboot_if_required: true
    # Reboot timeout (seconds)
    reboot_timeout: 900

  # Clears down hosts e.g. Chronos
  pre_tasks:
    - name: Drop unreachable hosts early
      ansible.builtin.ping:
      register: ping_result
      ignore_errors: true
    - name: End host if unreachable
      ansible.builtin.meta: end_host
      when: ping_result is failed

  tasks:
    - name: Refresh apt cache (if stale)
    # Ansible's apt module handles non-interactive use by default
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: "{{ cache_valid_time }}"
      tags: [apt, upgrade, maintenance]

    - name: Upgrade all packages to latest ({{ upgrade_type }})
      ansible.builtin.apt:
        upgrade: "{{ upgrade_type }}"   # "safe" or "dist"
      register: apt_upgrade_result
      tags: [apt, upgrade, maintenance]

    - name: Autoremove orphaned packages
      ansible.builtin.apt:
        autoremove: true
      tags: [apt, cleanup, maintenance]

    - name: Autoclean apt cache
      ansible.builtin.apt:
        autoclean: true
      tags: [apt, cleanup, maintenance]

    - name: Clean apt cache (optional but tidy)
      ansible.builtin.apt:
        clean: true
      tags: [apt, cleanup, maintenance]

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      changed_when: false
      tags: [apt, reboot, maintenance]

    - name: Reboot if required
      ansible.builtin.reboot:
        reboot_timeout: "{{ reboot_timeout }}"
      when:
        - reboot_if_required
        - reboot_required_file.stat.exists
      tags: [apt, reboot, maintenance]
