- name: Install & enroll Zabbix Agent2
  hosts: all:!zabbix
  become: true
  gather_facts: true

  # Pull from extra-vars or env FIRST, fall back to group_vars if set there
  vars:
    zbx_server_effective: "{{ lookup('env','ZBX_SERVER') | default('', true) }}"
    zbx_psk_identity_effective: "{{ lookup('env','ZBX_PSK_IDENTITY') | default('', true) }}"
    zbx_psk_effective: "{{ lookup('env','ZBX_PSK') | default('', true) }}"

    zbx_repo_base: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution | lower }}"
    zbx_repo_dist: "{{ ansible_lsb.codename | default(ansible_distribution_release) }}"
    zbx_apt_list: "/etc/apt/sources.list.d/zabbix.list"
    zbx_gpg_key_url: "https://repo.zabbix.com/zabbix-official-repo.key"
    zbx_psk_file: "/etc/zabbix/zabbix_agent2.psk"
    zbx_agent_conf: "/etc/zabbix/zabbix_agent2.conf"

  pre_tasks:
    - name: Validate secrets are present (fail fast)
      assert:
        that:
          - (zbx_server_effective | length) > 0
          - (zbx_psk_identity_effective | length) > 0
          - (zbx_psk_effective | length) > 0
        fail_msg: "ZBX_SERVER / ZBX_PSK_IDENTITY / ZBX_PSK must be provided via Semaphore Environment variables."

    - name: Remove manual Zabbix repo file if present (avoid conflicts)
      file:
        path: "/etc/apt/sources.list.d/zabbix.list"
        state: absent

    - name: Ensure base packages
      apt:
        name: [ca-certificates, gnupg, lsb-release, curl, python3-apt]
        state: present
        update_cache: yes

    - name: Compute zabbix-release tag (debianN / ubuntuXX.XX)
      set_fact:
        zbx_os_id: "{{ ansible_distribution | lower }}"
        zbx_release_tag: >-
          {{ ('debian' ~ ansible_distribution_major_version)
             if (ansible_distribution | lower) == 'debian'
             else ('ubuntu' ~ ansible_distribution_version) }}

    - name: Download Zabbix release package {{ zabbix_version }} for {{ zbx_release_tag }}
      get_url:
        url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/{{ zbx_os_id }}/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_version }}+{{ zbx_release_tag }}_all.deb"
        dest: "/tmp/zabbix-release_{{ zabbix_version }}+{{ zbx_release_tag }}.deb"
        mode: "0644"

    - name: Install Zabbix repo (zabbix-release)
      apt:
        deb: "/tmp/zabbix-release_{{ zabbix_version }}+{{ zbx_release_tag }}.deb"

    - name: apt update after adding zabbix-release
      apt:
        update_cache: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install zabbix-agent2
      apt:
        name: "zabbix-agent2"
        state: present
        update_cache: yes

    - name: Write PSK securely
      copy:
        dest: "{{ zbx_psk_file }}"
        content: "{{ zbx_psk_effective }}\n"
        owner: zabbix
        group: zabbix
        mode: "0400"

    - name: Force Hostname to actual hostname (override default "Zabbix server")
      lineinfile:
        path: "{{ zbx_agent_conf }}"
        regexp: '^Hostname='
        line: "Hostname={{ ansible_hostname }}"
      notify: restart zabbix-agent2

    - name: Remove HostnameItem to avoid conflict
      lineinfile:
        path: "{{ zbx_agent_conf }}"
        regexp: '^HostnameItem='
        state: absent
      notify: restart zabbix-agent2

    - name: Configure zabbix_agent2.conf
      blockinfile:
        path: "{{ zbx_agent_conf }}"
        marker: "# {mark} ANSIBLE MANAGED ZABBIX AGENT2"
        block: |
          Hostname={{ ansible_hostname }}

          Server={{ zbx_server_effective }}
          ServerActive={{ zbx_server_effective }}:{{ zbx_server_port }}
          ListenPort={{ zbx_listen_port }}

          HostMetadata={{ zbx_host_metadata }}

          TLSConnect=psk
          TLSAccept=psk
          TLSPSKIdentity={{ zbx_psk_identity_effective }}
          TLSPSKFile={{ zbx_psk_file }}
      notify: restart zabbix-agent2

    - name: Enable & start agent
      systemd:
        name: zabbix-agent2
        enabled: true
        state: started

  handlers:
    - name: restart zabbix-agent2
      systemd:
        name: zabbix-agent2
        state: restarted