---
- name: CHANGE ME
  hosts: all
  ignore_unreachable: true
  become: true
  gather_facts: false # handled by bootstrap-and-check.yml to ignore dead hosts

  vars:
    upgrade_type: "dist"
    cache_valid_time: 3600
    reboot_if_required: true
    reboot_timeout: 900

  pre_tasks:
    - name: Bootstrap & validate host reachability
      import_tasks: ../common/bootstrap-and-check.yml

  tasks:
    - name: CHANGE ME